services:
  - type: web
    name: hunyuan3d-server
    env: python
    buildCommand: pip install -r requirements_cloud.txt
    startCommand: uvicorn cloud_server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0